runtime: nodejs
env: flex

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "22"

instance_class: F1
automatic_scaling:
  max_num_instances: 1

handlers:
  - url: /.*
    script: auto